### ISSUE TITLE
Premiere version

### ISSUE THREAD

**Issue by Jkeez** [PolytechLyon/2019-isi3-graph-yalcin_oudjane#1]
bonjour, voici une première version du projet, nous aimerions avoir vos retours.

**Comment by RiwanODN** [comment]
Bonjour monsieur Caron,
je vous ai envoyé un email.
Notre projet est terminé,
pourriez-vous y jeter un coup d'oeil? 
Merci par avance,
Riwan,

**Comment by Slashgear** [comment]
- Merci de ne pas commit vos debug merci

https://github.com/PolytechLyon/2019-isi3-graph-yalcin_oudjane/blob/4259aad931d5c1e4758a5362ebb9cc885a37d1ec/src/main/java/graph/Graph.java#L47

Pourquoi créer une variable ici ?

https://github.com/PolytechLyon/2019-isi3-graph-yalcin_oudjane/blob/4259aad931d5c1e4758a5362ebb9cc885a37d1ec/src/main/java/graph/Graph.java#L48

N'y a-t-il pas plus simple ?

https://github.com/PolytechLyon/2019-isi3-graph-yalcin_oudjane/blob/4259aad931d5c1e4758a5362ebb9cc885a37d1ec/src/main/java/graph/Graph.java#L53

Vous pourriez directement construire l'instance de Graph sans passer par un constructeur 💡 

```java
private Toto toto = new Toto();
```

La méthode toString est dupliquée

https://github.com/PolytechLyon/2019-isi3-graph-yalcin_oudjane/blob/4259aad931d5c1e4758a5362ebb9cc885a37d1ec/src/main/java/graph/UndirectedGraph.java#L52

**Comment by Jkeez** [comment]
Pourrions nous avoir un deuxième avis s'il vous plait ? Nous avons pris compte de vos remarques.
